remote_theme: just-the-docs/just-the-docs

title: rTechsupport Wiki
description: An opensource wiki for the community
url: 'https://wiki.rtech.support'

#logo: '/assets/rTS.png'
site_favicon: '/assets/rTS.ico'

sticky_navigation: true

back_to_top: true
back_to_top_text: "Back to top"

last_edit_timestamp: true

gh_edit_link: false

color_scheme: dark
