remote_theme: just-the-docs/just-the-docs

site_author: PipeItToDevNull
repo_url: 'https://github.com/PipeItToDevNull/rTS_Wiki'
edit_on_github: true
github_docs_folder: true
logo: ''
site_favicon: ''
sticky_navigation: true
prev_next_buttons_location: None
prev_next_buttons_location: top
prev_next_buttons_location: bottom
prev_next_buttons_location: both
color_scheme: dark
