remote_theme: just-the-docs/just-the-docs

title: rTechsupport Wiki
description: An opensource wiki for the community
url: 'https://wiki.rtech.support'

aux_links:
    "Join our Discord!":
        - "https://discord.com/invite/2EDwzWa"

sticky_navigation: true

back_to_top: true
back_to_top_text: "Back to top"

last_edit_timestamp: true

gh_edit_link: false

color_scheme: light

# This helps with local development
plugins:
    - jekyll-remote-theme

